base_model: NousResearch/Llama-3.2-1B
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/gratefulgpt_model

datasets:
  - path: /workspace/data/gratefulgpt_dataset.jsonl
    type: completion  # Raw completion training on our text data

val_set_size: 0.05
output_dir: /workspace/data/axolotl-artifacts/gratefulgpt-outputs

adapter: qlora
lora_model_dir:

sequence_len: 2048
sample_packing: true
eval_sample_packing: true
pad_to_sequence_len: true

load_in_4bit: true
load_in_8bit: false

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_project: 
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 1  # Conservative for A6000 48GB
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

bf16: auto
tf32: false

gradient_checkpointing: true
resume_from_checkpoint:
logging_steps: 10
flash_attention: true

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_steps: 100
evals_per_epoch: 2
saves_per_epoch: 1
weight_decay: 0.01

special_tokens:
  pad_token: "<|end_of_text|>"

# Disable vLLM completely
inference: false